DROP TABLE IF EXISTS User;
DROP TABLE IF EXISTS Subject;
DROP TABLE IF EXISTS Enrolment;
DROP TABLE IF EXISTS SingleLesson;
DROP TABLE IF EXISTS TrustedUsers;
DROP TABLE IF EXISTS RelatedSubjects;

CREATE TABLE User (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	Email TEXT UNIQUE NOT NULL,
	FirstName TEXT NOT NULL,
	Surname TEXT NOT NULL,
	YearGroup TEXT NOT NULL,
	Private INTEGER NOT NULL,
	Secret TEXT UNIQUE NOT NULL
);

CREATE TABLE Subject (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	Name TEXT NOT NULL,
	Level INTEGER,
	Qualification TEXT
);

CREATE TABLE Enrolment (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	UserID INTEGER NOT NULL,
	SubjectID INTEGER NOT NULL,
	Block TEXT NOT NULL,
	UNIQUE(UserID, SubjectID),
	FOREIGN KEY (UserID) REFERENCES User (ID),
	FOREIGN KEY (SubjectID) REFERENCES Subject (ID)
);

CREATE TABLE SingleLesson (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	EnrolmentID INTEGER NOT NULL,
	Day TEXT NOT NULL,
	Period INTEGER NOT NULL,
	FOREIGN KEY (EnrolmentID) REFERENCES Enrolment (ID)
);

CREATE TABLE TrustedUsers (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	UserID1 INTEGER NOT NULL,
	UserID2 INTEGER NOT NULL,
	UNIQUE(UserID1, UserID2),
	FOREIGN KEY (UserID1) REFERENCES User (ID),
	FOREIGN KEY (UserID2) REFERENCES User (ID)
);